import { 
  User, 
  Ticket, 
  Employee, 
  AuditLog, 
  DashboardStats,
  QueueItem,
  Message
} from './types';

export const mockUsers: Record<string, User> = {
  'admin-1': {
    id: 'admin-1',
    email: 'admin@taxcrm.com',
    name: 'Sarah Johnson',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    createdAt: new Date('2023-01-15'),
  },
  'employee-1': {
    id: 'employee-1',
    email: 'employee@taxcrm.com',
    name: 'Michael Chen',
    role: 'employee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    createdAt: new Date('2023-06-20'),
  },
  'employee-2': {
    id: 'employee-2',
    email: 'james.wilson@taxcrm.com',
    name: 'James Wilson',
    role: 'employee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    createdAt: new Date('2023-07-10'),
  },
  'client-1': {
    id: 'client-1',
    email: 'client@taxcrm.com',
    name: 'Robert Smith',
    role: 'client',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    createdAt: new Date('2024-01-05'),
  },
  'client-2': {
    id: 'client-2',
    email: 'emma.davis@email.com',
    name: 'Emma Davis',
    role: 'client',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    createdAt: new Date('2024-02-10'),
  },
};

export const mockEmployees: Employee[] = [
  {
    id: 'employee-1',
    name: 'Michael Chen',
    email: 'michael.chen@taxcrm.com',
    role: 'employee',
    department: 'Individual Tax',
    status: 'active',
    hireDate: new Date('2023-06-20'),
    createdAt: new Date('2023-06-20'),
  },
  {
    id: 'employee-2',
    name: 'James Wilson',
    email: 'james.wilson@taxcrm.com',
    role: 'employee',
    department: 'Business Tax',
    status: 'active',
    hireDate: new Date('2023-07-10'),
    createdAt: new Date('2023-07-10'),
  },
  {
    id: 'employee-3',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@taxcrm.com',
    role: 'employee',
    department: 'Audit & Assurance',
    status: 'active',
    hireDate: new Date('2023-09-01'),
    createdAt: new Date('2023-09-01'),
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 'ticket-001',
    clientId: 'client-1',
    clientName: 'Robert Smith',
    clientEmail: 'robert.smith@email.com',
    subject: '2024 Individual Tax Return',
    description: 'Annual tax return preparation for 2024',
    stage: 'document-collection',
    status: 'in-progress',
    priority: 'high',
    assignedToId: 'employee-1',
    assignedToName: 'Michael Chen',
    taxYear: 2024,
    filingType: 'Individual 1040',
    documents: [
      {
        id: 'doc-001',
        ticketId: 'ticket-001',
        name: 'W2_2024.pdf',
        type: 'application/pdf',
        size: 245000,
        url: '/documents/w2_2024.pdf',
        uploadedBy: 'client-1',
        uploadedAt: new Date('2024-02-15'),
      },
      {
        id: 'doc-002',
        ticketId: 'ticket-001',
        name: '1099-INT_Statement.pdf',
        type: 'application/pdf',
        size: 120000,
        url: '/documents/1099_int.pdf',
        uploadedBy: 'client-1',
        uploadedAt: new Date('2024-02-16'),
      },
    ],
    messages: [
      {
        id: 'msg-001',
        ticketId: 'ticket-001',
        senderId: 'employee-1',
        senderName: 'Michael Chen',
        senderRole: 'employee',
        content: 'Hi Robert, I received your W2 forms. I need a few more documents to complete your return. Could you send your mortgage interest statement?',
        createdAt: new Date('2024-02-17'),
        isInternal: false,
      },
    ],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-17'),
    dueDate: new Date('2024-04-15'),
  },
  {
    id: 'ticket-002',
    clientId: 'client-2',
    clientName: 'Emma Davis',
    clientEmail: 'emma.davis@email.com',
    subject: 'Small Business Tax Return - 2024',
    description: 'Tax return for consulting business',
    stage: 'review',
    status: 'in-progress',
    priority: 'medium',
    assignedToId: 'employee-2',
    assignedToName: 'James Wilson',
    taxYear: 2024,
    filingType: 'S-Corporation 1120-S',
    documents: [
      {
        id: 'doc-003',
        ticketId: 'ticket-002',
        name: 'BusinessExpenses_2024.xlsx',
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        size: 350000,
        url: '/documents/business_expenses.xlsx',
        uploadedBy: 'client-2',
        uploadedAt: new Date('2024-02-14'),
      },
    ],
    messages: [],
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-14'),
    dueDate: new Date('2024-03-31'),
  },
  {
    id: 'ticket-003',
    clientId: 'client-1',
    clientName: 'Robert Smith',
    clientEmail: 'robert.smith@email.com',
    subject: 'Previous Year Amendment - 2023',
    description: 'Amendment for 2023 tax year - additional deductions discovered',
    stage: 'amendment',
    status: 'open',
    priority: 'low',
    assignedToId: 'employee-3',
    assignedToName: 'Lisa Anderson',
    taxYear: 2023,
    filingType: 'Individual 1040',
    documents: [],
    messages: [],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    ticketId: 'ticket-001',
    senderId: 'employee-1',
    senderName: 'Michael Chen',
    senderRole: 'employee',
    content: 'Hi Robert, I received your W2 forms. I need a few more documents to complete your return. Could you send your mortgage interest statement?',
    createdAt: new Date('2024-02-17'),
    isInternal: false,
  },
  {
    id: 'msg-002',
    ticketId: 'ticket-001',
    senderId: 'client-1',
    senderName: 'Robert Smith',
    senderRole: 'client',
    content: 'Sure, I can send that. I\'ll upload it by tomorrow.',
    createdAt: new Date('2024-02-17'),
    isInternal: false,
  },
  {
    id: 'msg-003',
    ticketId: 'ticket-001',
    senderId: 'employee-1',
    senderName: 'Michael Chen',
    senderRole: 'employee',
    content: 'Internal note: Reviewed all documents, everything looks complete. Ready for preparation phase.',
    createdAt: new Date('2024-02-18'),
    isInternal: true,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    userId: 'admin-1',
    userName: 'Sarah Johnson',
    action: 'Created',
    resourceType: 'Ticket',
    resourceId: 'ticket-001',
    timestamp: new Date('2024-02-10'),
    details: { stage: 'intake' },
  },
  {
    id: 'audit-002',
    userId: 'employee-1',
    userName: 'Michael Chen',
    action: 'Updated',
    resourceType: 'Ticket',
    resourceId: 'ticket-001',
    timestamp: new Date('2024-02-17'),
    details: { stage: 'document-collection', status: 'in-progress' },
  },
  {
    id: 'audit-003',
    userId: 'admin-1',
    userName: 'Sarah Johnson',
    action: 'Created',
    resourceType: 'Employee',
    resourceId: 'employee-3',
    timestamp: new Date('2023-09-01'),
    details: { name: 'Lisa Anderson', department: 'Audit & Assurance' },
  },
];

export const mockDashboardStats: DashboardStats = {
  totalTickets: 28,
  openTickets: 12,
  completedThisMonth: 6,
  overdueTasks: 2,
  stageBreakdown: {
    intake: 3,
    'document-collection': 5,
    review: 4,
    preparation: 6,
    filing: 3,
    amendment: 1,
    'follow-up': 4,
    closed: 2,
    'on-hold': 0,
  },
};

export const mockQueueItems: QueueItem[] = [
  {
    id: 'queue-001',
    ticketId: 'ticket-001',
    clientName: 'Robert Smith',
    stage: 'document-collection',
    priority: 'high',
    daysInQueue: 7,
    assignedTo: 'Michael Chen',
  },
  {
    id: 'queue-002',
    ticketId: 'ticket-002',
    clientName: 'Emma Davis',
    stage: 'review',
    priority: 'medium',
    daysInQueue: 5,
    assignedTo: 'James Wilson',
  },
  {
    id: 'queue-003',
    ticketId: 'ticket-003',
    clientName: 'Robert Smith',
    stage: 'amendment',
    priority: 'low',
    daysInQueue: 30,
    assignedTo: 'Lisa Anderson',
  },
];
