import { 
  User, 
  Ticket, 
  Employee, 
  AuditLog, 
  DashboardStats,
  QueueItem,
  Message
} from './types';

export const mockUsers: Record<string, User> = {
  'admin-1': {
    id: 'admin-1',
    email: 'admin@taxcrm.com',
    name: 'Sarah Johnson',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    createdAt: new Date('2023-01-15'),
  },
  'employee-1': {
    id: 'employee-1',
    email: 'employee@taxcrm.com',
    name: 'Michael Chen',
    role: 'employee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    createdAt: new Date('2023-06-20'),
  },
  'employee-2': {
    id: 'employee-2',
    email: 'james.wilson@taxcrm.com',
    name: 'James Wilson',
    role: 'employee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    createdAt: new Date('2023-07-10'),
  },
  'client-1': {
    id: 'client-1',
    email: 'client@taxcrm.com',
    name: 'Robert Smith',
    role: 'client',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    createdAt: new Date('2024-01-05'),
  },
  'client-2': {
    id: 'client-2',
    email: 'emma.davis@email.com',
    name: 'Emma Davis',
    role: 'client',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    createdAt: new Date('2024-02-10'),
  },
};

export const mockEmployees: Employee[] = [
  {
    id: 'employee-1',
    name: 'Michael Chen',
    email: 'michael.chen@taxcrm.com',
    role: 'employee',
    department: 'Individual Tax',
    status: 'active',
    hireDate: new Date('2023-06-20'),
    createdAt: new Date('2023-06-20'),
  },
  {
    id: 'employee-2',
    name: 'James Wilson',
    email: 'james.wilson@taxcrm.com',
    role: 'employee',
    department: 'Business Tax',
    status: 'active',
    hireDate: new Date('2023-07-10'),
    createdAt: new Date('2023-07-10'),
  },
  {
    id: 'employee-3',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@taxcrm.com',
    role: 'employee',
    department: 'Audit & Assurance',
    status: 'active',
    hireDate: new Date('2023-09-01'),
    createdAt: new Date('2023-09-01'),
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 'ticket-001',
    clientId: 'client-1',
    clientName: 'Robert Smith',
    clientEmail: 'robert.smith@email.com',
    subject: '2024 Individual Tax Return',
    description: 'Annual tax return preparation for 2024',
    stage: 'draft-sent',
    status: 'in-progress',
    priority: 'high',
    assignedToId: 'employee-1',
    assignedToName: 'Michael Chen',
    taxYear: 2024,
    filingType: 'Individual 1040',
    shortCode: '22497',
    drafts: [
      { id: 'dr-1', name: 'Draft_2024_Federal_v2.pdf', sharedAt: new Date('2026-04-05') },
      { id: 'dr-2', name: 'Draft_2024_State_CA_v1.pdf', sharedAt: new Date('2026-04-04') },
      { id: 'dr-3', name: 'Notes_from_preparer.txt', sharedAt: new Date('2026-04-03') },
    ],
    invoices: [
      {
        id: 'inv-1',
        invoiceNumber: 'INV-2026-0142',
        description: 'Tax prep — 2024 Individual',
        amountCents: 45000,
        status: 'unpaid',
        dueDate: new Date('2026-04-20'),
      },
      {
        id: 'inv-2',
        invoiceNumber: 'INV-2025-0099',
        description: 'Tax prep — 2023 Individual (paid)',
        amountCents: 42500,
        status: 'paid',
        paidAt: new Date('2025-04-12'),
      },
    ],
    finalDocuments: [],
    documents: [
      {
        id: 'doc-001',
        ticketId: 'ticket-001',
        name: 'W2_2024.pdf',
        type: 'application/pdf',
        size: 245000,
        url: '/documents/w2_2024.pdf',
        uploadedBy: 'client-1',
        uploadedAt: new Date('2026-04-06'),
      },
      {
        id: 'doc-002',
        ticketId: 'ticket-001',
        name: '1099_INT.pdf',
        type: 'application/pdf',
        size: 120000,
        url: '/documents/1099_int.pdf',
        uploadedBy: 'client-1',
        uploadedAt: new Date('2026-04-06'),
      },
      {
        id: 'doc-zip',
        ticketId: 'ticket-001',
        name: 'Deduction_Receipts.zip',
        type: 'application/zip',
        size: 890000,
        url: '/documents/deduction_receipts.zip',
        uploadedBy: 'client-1',
        uploadedAt: new Date('2026-04-06'),
      },
    ],
    messages: [
      {
        id: 'msg-001',
        ticketId: 'ticket-001',
        senderId: 'employee-1',
        senderName: 'Michael Chen',
        senderRole: 'employee',
        content: 'Draft return has been prepared and sent for your review. Please review and let me know if you have any questions.',
        createdAt: new Date('2024-02-17'),
        isInternal: false,
      },
    ],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-17'),
    dueDate: new Date('2024-04-15'),
  },
  {
    id: 'ticket-002',
    clientId: 'client-2',
    clientName: 'Emma Davis',
    clientEmail: 'emma.davis@email.com',
    subject: 'Small Business Tax Return - 2024',
    description: 'Tax return for consulting business',
    stage: 'under-prep',
    status: 'in-progress',
    priority: 'medium',
    assignedToId: 'employee-2',
    assignedToName: 'James Wilson',
    taxYear: 2024,
    filingType: 'S-Corporation 1120-S',
    documents: [
      {
        id: 'doc-003',
        ticketId: 'ticket-002',
        name: 'BusinessExpenses_2024.xlsx',
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        size: 350000,
        url: '/documents/business_expenses.xlsx',
        uploadedBy: 'client-2',
        uploadedAt: new Date('2024-02-14'),
      },
    ],
    messages: [],
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-14'),
    dueDate: new Date('2024-03-31'),
  },
  {
    id: 'ticket-003',
    clientId: 'client-1',
    clientName: 'Robert Smith',
    clientEmail: 'robert.smith@email.com',
    subject: '2025 Individual Tax Return',
    description: 'Quarterly estimated tax payment',
    stage: 'filing-completed',
    status: 'completed',
    priority: 'low',
    assignedToId: 'employee-3',
    assignedToName: 'Lisa Anderson',
    taxYear: 2025,
    filingType: 'Individual 1040',
    shortCode: '22197',
    drafts: [],
    invoices: [],
    finalDocuments: [
      { id: 'fd-1', name: 'Signed_1040_2025.pdf', availableAt: new Date('2026-03-10') },
      { id: 'fd-2', name: 'Filing_confirmation.pdf', availableAt: new Date('2026-03-10') },
    ],
    documents: [],
    messages: [],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'ticket-004',
    clientId: 'client-2',
    clientName: 'Emma Davis',
    clientEmail: 'emma.davis@email.com',
    subject: '8879 Electronic Signature',
    description: 'Waiting for client signature on Form 8879',
    stage: '8879-sent',
    status: 'pending',
    priority: 'high',
    assignedToId: 'employee-2',
    assignedToName: 'James Wilson',
    taxYear: 2024,
    filingType: 'S-Corporation 1120-S',
    documents: [],
    messages: [],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'ticket-005',
    clientId: 'client-1',
    clientName: 'Robert Smith',
    clientEmail: 'robert.smith@email.com',
    subject: 'Payment Due',
    description: 'Awaiting payment for tax preparation services',
    stage: 'payment-received',
    status: 'completed',
    priority: 'medium',
    assignedToId: 'employee-1',
    assignedToName: 'Michael Chen',
    taxYear: 2024,
    filingType: 'Individual 1040',
    shortCode: '22301',
    drafts: [],
    invoices: [],
    finalDocuments: [],
    documents: [],
    messages: [],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-22'),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    ticketId: 'ticket-001',
    senderId: 'employee-1',
    senderName: 'Michael Chen',
    senderRole: 'employee',
    content: 'Draft return has been prepared and sent for your review. Please review and let me know if you have any questions.',
    createdAt: new Date('2024-02-17'),
    isInternal: false,
  },
  {
    id: 'msg-002',
    ticketId: 'ticket-001',
    senderId: 'client-1',
    senderName: 'Robert Smith',
    senderRole: 'client',
    content: 'I reviewed the draft. Everything looks good. When can we proceed with filing?',
    createdAt: new Date('2024-02-18'),
    isInternal: false,
  },
  {
    id: 'msg-003',
    ticketId: 'ticket-001',
    senderId: 'employee-1',
    senderName: 'Michael Chen',
    senderRole: 'employee',
    content: 'Internal note: Client approved draft. Ready to move to 8879 stage.',
    createdAt: new Date('2024-02-18'),
    isInternal: true,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    userId: 'admin-1',
    userName: 'Sarah Johnson',
    action: 'Created',
    resourceType: 'Ticket',
    resourceId: 'ticket-001',
    timestamp: new Date('2024-02-10'),
    details: { stage: 'pending-info' },
  },
  {
    id: 'audit-002',
    userId: 'employee-1',
    userName: 'Michael Chen',
    action: 'Updated',
    resourceType: 'Ticket',
    resourceId: 'ticket-001',
    timestamp: new Date('2024-02-17'),
    details: { stage: 'draft-sent', status: 'in-progress' },
  },
  {
    id: 'audit-003',
    userId: 'admin-1',
    userName: 'Sarah Johnson',
    action: 'Created',
    resourceType: 'Employee',
    resourceId: 'employee-3',
    timestamp: new Date('2023-09-01'),
    details: { name: 'Lisa Anderson', department: 'Audit & Assurance' },
  },
];

export const mockDashboardStats: DashboardStats = {
  totalTickets: 28,
  openTickets: 12,
  completedThisMonth: 6,
  overdueTasks: 2,
  stageBreakdown: {
    'pending-info': 3,
    'under-prep': 5,
    'draft-sent': 4,
    'awaiting-approval': 3,
    'payment-received': 2,
    '8879-sent': 3,
    '8879-received': 2,
    'filing-completed': 4,
    'closed': 2,
  },
};

export const mockQueueItems: QueueItem[] = [
  {
    id: 'queue-001',
    ticketId: 'ticket-001',
    clientName: 'Robert Smith',
    stage: 'draft-sent',
    priority: 'high',
    daysInQueue: 7,
    assignedTo: 'Michael Chen',
  },
  {
    id: 'queue-002',
    ticketId: 'ticket-002',
    clientName: 'Emma Davis',
    stage: 'under-prep',
    priority: 'medium',
    daysInQueue: 5,
    assignedTo: 'James Wilson',
  },
  {
    id: 'queue-003',
    ticketId: 'ticket-004',
    clientName: 'Emma Davis',
    stage: '8879-sent',
    priority: 'high',
    daysInQueue: 2,
    assignedTo: 'James Wilson',
  },
];
