-- Add staff-only flag to documents and update document_category enum for staff-generated documents
-- This allows PDFs generated by staff to be hidden from clients

-- Update document_category enum to include staff_generated
ALTER TYPE public.document_category ADD VALUE 'staff_generated';

-- Add is_staff_only column to documents table
ALTER TABLE public.documents 
ADD COLUMN IF NOT EXISTS is_staff_only BOOLEAN DEFAULT FALSE;

-- Add name and url columns to documents table if they don't exist
-- (These might be needed for the PDF generation functionality)
ALTER TABLE public.documents 
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS url TEXT;

-- Update existing documents to have a name based on original_filename if name is null
UPDATE public.documents 
SET name = COALESCE(original_filename, 'Document') 
WHERE name IS NULL;

-- Create index for staff-only filtering
CREATE INDEX IF NOT EXISTS idx_documents_staff_only ON public.documents (ticket_id, is_staff_only);

-- Update RLS policies to handle staff-only documents
-- Clients should not see staff-only documents
DROP POLICY IF EXISTS "documents_select_access" ON public.documents;

CREATE POLICY "documents_select_access"
  ON public.documents FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.tickets t
      WHERE t.id = documents.ticket_id AND public.can_access_ticket(t)
    )
    AND (
      -- Staff can see all documents
      public.is_staff()
      -- Clients can only see non-staff-only documents
      OR (is_staff_only = FALSE OR is_staff_only IS NULL)
    )
  );